version: '2.2'

services:
  postgres:
    image: postgres:14.4-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    volumes:
      - .pg_data:/var/lib/postgresql/data
    restart: on-failure
    stop_grace_period: 10s
    mem_limit: 1G
    memswap_limit: 1G
    pids_limit: 100

  mailbox:
    build: .
    restart: on-failure
    stop_grace_period: 10s
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "3131:3131"
    volumes:
      - .data:/var/data
    ulimits:
      nofile:
        soft: 12000
        hard: 12000
    mem_limit: 1G
    memswap_limit: 1G
    pids_limit: 100
