// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.2
// source: omc.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OMCClient is the client API for OMC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OMCClient interface {
	CreateRealm(ctx context.Context, in *Realm, opts ...grpc.CallOption) (*Empty, error)
	GetRealms(ctx context.Context, in *RealmId, opts ...grpc.CallOption) (OMC_GetRealmsClient, error)
	GetState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*State, error)
	SendAction(ctx context.Context, in *Action, opts ...grpc.CallOption) (*State, error)
}

type oMCClient struct {
	cc grpc.ClientConnInterface
}

func NewOMCClient(cc grpc.ClientConnInterface) OMCClient {
	return &oMCClient{cc}
}

func (c *oMCClient) CreateRealm(ctx context.Context, in *Realm, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto_omc.OMC/CreateRealm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oMCClient) GetRealms(ctx context.Context, in *RealmId, opts ...grpc.CallOption) (OMC_GetRealmsClient, error) {
	stream, err := c.cc.NewStream(ctx, &OMC_ServiceDesc.Streams[0], "/proto_omc.OMC/GetRealms", opts...)
	if err != nil {
		return nil, err
	}
	x := &oMCGetRealmsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type OMC_GetRealmsClient interface {
	Recv() (*Realm, error)
	grpc.ClientStream
}

type oMCGetRealmsClient struct {
	grpc.ClientStream
}

func (x *oMCGetRealmsClient) Recv() (*Realm, error) {
	m := new(Realm)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *oMCClient) GetState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*State, error) {
	out := new(State)
	err := c.cc.Invoke(ctx, "/proto_omc.OMC/GetState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oMCClient) SendAction(ctx context.Context, in *Action, opts ...grpc.CallOption) (*State, error) {
	out := new(State)
	err := c.cc.Invoke(ctx, "/proto_omc.OMC/SendAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OMCServer is the server API for OMC service.
// All implementations must embed UnimplementedOMCServer
// for forward compatibility
type OMCServer interface {
	CreateRealm(context.Context, *Realm) (*Empty, error)
	GetRealms(*RealmId, OMC_GetRealmsServer) error
	GetState(context.Context, *Empty) (*State, error)
	SendAction(context.Context, *Action) (*State, error)
	mustEmbedUnimplementedOMCServer()
}

// UnimplementedOMCServer must be embedded to have forward compatible implementations.
type UnimplementedOMCServer struct {
}

func (UnimplementedOMCServer) CreateRealm(context.Context, *Realm) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRealm not implemented")
}
func (UnimplementedOMCServer) GetRealms(*RealmId, OMC_GetRealmsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetRealms not implemented")
}
func (UnimplementedOMCServer) GetState(context.Context, *Empty) (*State, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedOMCServer) SendAction(context.Context, *Action) (*State, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendAction not implemented")
}
func (UnimplementedOMCServer) mustEmbedUnimplementedOMCServer() {}

// UnsafeOMCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OMCServer will
// result in compilation errors.
type UnsafeOMCServer interface {
	mustEmbedUnimplementedOMCServer()
}

func RegisterOMCServer(s grpc.ServiceRegistrar, srv OMCServer) {
	s.RegisterService(&OMC_ServiceDesc, srv)
}

func _OMC_CreateRealm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Realm)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OMCServer).CreateRealm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_omc.OMC/CreateRealm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OMCServer).CreateRealm(ctx, req.(*Realm))
	}
	return interceptor(ctx, in, info, handler)
}

func _OMC_GetRealms_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RealmId)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OMCServer).GetRealms(m, &oMCGetRealmsServer{stream})
}

type OMC_GetRealmsServer interface {
	Send(*Realm) error
	grpc.ServerStream
}

type oMCGetRealmsServer struct {
	grpc.ServerStream
}

func (x *oMCGetRealmsServer) Send(m *Realm) error {
	return x.ServerStream.SendMsg(m)
}

func _OMC_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OMCServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_omc.OMC/GetState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OMCServer).GetState(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OMC_SendAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Action)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OMCServer).SendAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_omc.OMC/SendAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OMCServer).SendAction(ctx, req.(*Action))
	}
	return interceptor(ctx, in, info, handler)
}

// OMC_ServiceDesc is the grpc.ServiceDesc for OMC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OMC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto_omc.OMC",
	HandlerType: (*OMCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRealm",
			Handler:    _OMC_CreateRealm_Handler,
		},
		{
			MethodName: "GetState",
			Handler:    _OMC_GetState_Handler,
		},
		{
			MethodName: "SendAction",
			Handler:    _OMC_SendAction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetRealms",
			Handler:       _OMC_GetRealms_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "omc.proto",
}
