// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.2
// source: omc.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OMCClient is the client API for OMC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OMCClient interface {
	PutBlock(ctx context.Context, in *Block, opts ...grpc.CallOption) (*Empty, error)
	GetBlocks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (OMC_GetBlocksClient, error)
	PutShared(ctx context.Context, in *Block, opts ...grpc.CallOption) (*SharedBlockCreateResponse, error)
	GetShared(ctx context.Context, in *GetSharedBlock, opts ...grpc.CallOption) (*SharedBlock, error)
}

type oMCClient struct {
	cc grpc.ClientConnInterface
}

func NewOMCClient(cc grpc.ClientConnInterface) OMCClient {
	return &oMCClient{cc}
}

func (c *oMCClient) PutBlock(ctx context.Context, in *Block, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto_omc.OMC/PutBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oMCClient) GetBlocks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (OMC_GetBlocksClient, error) {
	stream, err := c.cc.NewStream(ctx, &OMC_ServiceDesc.Streams[0], "/proto_omc.OMC/GetBlocks", opts...)
	if err != nil {
		return nil, err
	}
	x := &oMCGetBlocksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type OMC_GetBlocksClient interface {
	Recv() (*Block, error)
	grpc.ClientStream
}

type oMCGetBlocksClient struct {
	grpc.ClientStream
}

func (x *oMCGetBlocksClient) Recv() (*Block, error) {
	m := new(Block)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *oMCClient) PutShared(ctx context.Context, in *Block, opts ...grpc.CallOption) (*SharedBlockCreateResponse, error) {
	out := new(SharedBlockCreateResponse)
	err := c.cc.Invoke(ctx, "/proto_omc.OMC/PutShared", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oMCClient) GetShared(ctx context.Context, in *GetSharedBlock, opts ...grpc.CallOption) (*SharedBlock, error) {
	out := new(SharedBlock)
	err := c.cc.Invoke(ctx, "/proto_omc.OMC/GetShared", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OMCServer is the server API for OMC service.
// All implementations must embed UnimplementedOMCServer
// for forward compatibility
type OMCServer interface {
	PutBlock(context.Context, *Block) (*Empty, error)
	GetBlocks(*Empty, OMC_GetBlocksServer) error
	PutShared(context.Context, *Block) (*SharedBlockCreateResponse, error)
	GetShared(context.Context, *GetSharedBlock) (*SharedBlock, error)
	mustEmbedUnimplementedOMCServer()
}

// UnimplementedOMCServer must be embedded to have forward compatible implementations.
type UnimplementedOMCServer struct {
}

func (UnimplementedOMCServer) PutBlock(context.Context, *Block) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutBlock not implemented")
}
func (UnimplementedOMCServer) GetBlocks(*Empty, OMC_GetBlocksServer) error {
	return status.Errorf(codes.Unimplemented, "method GetBlocks not implemented")
}
func (UnimplementedOMCServer) PutShared(context.Context, *Block) (*SharedBlockCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutShared not implemented")
}
func (UnimplementedOMCServer) GetShared(context.Context, *GetSharedBlock) (*SharedBlock, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShared not implemented")
}
func (UnimplementedOMCServer) mustEmbedUnimplementedOMCServer() {}

// UnsafeOMCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OMCServer will
// result in compilation errors.
type UnsafeOMCServer interface {
	mustEmbedUnimplementedOMCServer()
}

func RegisterOMCServer(s grpc.ServiceRegistrar, srv OMCServer) {
	s.RegisterService(&OMC_ServiceDesc, srv)
}

func _OMC_PutBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Block)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OMCServer).PutBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_omc.OMC/PutBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OMCServer).PutBlock(ctx, req.(*Block))
	}
	return interceptor(ctx, in, info, handler)
}

func _OMC_GetBlocks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OMCServer).GetBlocks(m, &oMCGetBlocksServer{stream})
}

type OMC_GetBlocksServer interface {
	Send(*Block) error
	grpc.ServerStream
}

type oMCGetBlocksServer struct {
	grpc.ServerStream
}

func (x *oMCGetBlocksServer) Send(m *Block) error {
	return x.ServerStream.SendMsg(m)
}

func _OMC_PutShared_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Block)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OMCServer).PutShared(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_omc.OMC/PutShared",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OMCServer).PutShared(ctx, req.(*Block))
	}
	return interceptor(ctx, in, info, handler)
}

func _OMC_GetShared_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSharedBlock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OMCServer).GetShared(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_omc.OMC/GetShared",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OMCServer).GetShared(ctx, req.(*GetSharedBlock))
	}
	return interceptor(ctx, in, info, handler)
}

// OMC_ServiceDesc is the grpc.ServiceDesc for OMC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OMC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto_omc.OMC",
	HandlerType: (*OMCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutBlock",
			Handler:    _OMC_PutBlock_Handler,
		},
		{
			MethodName: "PutShared",
			Handler:    _OMC_PutShared_Handler,
		},
		{
			MethodName: "GetShared",
			Handler:    _OMC_GetShared_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetBlocks",
			Handler:       _OMC_GetBlocks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "omc.proto",
}
